### ISSUE TITLE
no result

### ISSUE THREAD

**Issue by jhercher** [fusepoolP3/p3-large-scale-script-js#2]
Hi Gabor,

I tried it with different GND IDs (I changed them in T0.txt), but always get  

```
undefined:168
    { "gndid": { "type": "uri", "value": 

```

Can you please check?

thx 
Johannes

**Comment by gaborremenyi** [comment]
Hi Johannes,

If you want the script to read the GND IDs from file you have to set 2 variables in the script first.
Line 70: var RUN_T0 = false;
Line 72: var resultT0 = 'T0.txt';

Otherwise it will fetch them by running the T0 query. If you've already done this and it's still not working please provide a little more information. I.e. the whole error msg from the console, and preferably the content of T0.txt.

Cheers,
Gabor

**Comment by ktk** [comment]
@jhercher sorry for the confusion, I will run the script directly on the server so you don't really have to run that yourself. It will probably take a while so it's best if we do that directly there.

**Comment by jhercher** [comment]
Hi gabor,
thanks for the tip. I see it tries to execute T0 which results in a timeout. The other steps seem to run normal. :+1:  I guess the results are stored on the server. Any chance to store them locally for debugging?

**Comment by gaborremenyi** [comment]
I'm not sure what you meant by storing the results locally, but the result of T0 query is stored in data/T0.txt: https://github.com/fusepoolP3/p3-large-scale-script-js/blob/master/data/T0.txt

**Comment by gaborremenyi** [comment]
As far as I know this issue no longer exists.
